### ISSUE TITLE
mvn clean install not working

### ISSUE THREAD

**Issue by avenash97** [DataFabricRus/NiFi-GCD-Job-Runner#1]
Failed to execute goal on project nifi-gcd-processors: Could not resolve dependencies for project cc.datafabric.nifi:nifi-gcd-processors:jar:1.0: Failure to find cc.datafabric.nifi:nif
i-gcd-services-api:jar:1.0-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapsh
ots has elapsed or updates are forced 

![image](https://user-images.githubusercontent.com/20367823/87400977-29e90900-c5d7-11ea-9486-d44728e59e1c.png)

**Comment by DramaticallyDecayed** [comment]
Have corrected the version for the dependency. Please, try once more. Thanks!
